name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run specific job'
        required: false
        type: boolean
        
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: 'Printing Custom Message'
      run: echo echo ${{ inputs.custom_message }} #New Message
       